[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "cython",
            "jinja2",
            "oldest-supported-numpy",
            "extension-helpers @ git+https://github.com/astropy/astropy-helpers@extension-helpers"]
